name: CI - Cypress Download Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false # https://github.com/cypress-io/github-action/issues/48
      matrix:
        containers: [1,2,4,5,6] # Uses 2 parallel instances

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Cypress run
        uses: cypress-io/github-action@v7
        with:
          browser: chrome   # downloads costumam ser mais estáveis no Chrome

        records: true
        parallel: true
      # Salva os arquivos baixados pra inspeção, se algum teste falhar
      - name: Upload downloads on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-downloads
          path: cypress/downloads


        env:
          # For recording and parallelization you must set your CYPRESS_RECORD_KEY
          # in GitHub repo → Settings → Secrets → Actions
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # Create a token https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}        